import type { CSSProperties, ReactNode } from 'react'
import { cn } from '@/lib/cn'
import { photos, type PhotoName } from '@/data/media'

/**
 * Photography.
 *
 * WHY THERE ARE PHOTOGRAPHS HERE AT ALL
 * The source documents specify illustration for Phase 1 and photography "once
 * available" in Phase 2, on the grounds that showing a campus that is not open
 * would be an overclaim. That reasoning is about *false* photographs — pictures
 * that imply an LBS KidZ classroom exists. It is not an argument against
 * showing what early childhood actually looks like.
 *
 * So photography is used, and the overclaim is prevented by what the site says
 * rather than by a notice about the pictures:
 *   - No photograph is captioned, framed or implied as an LBS KidZ campus,
 *     classroom, child, parent or educator. Nothing says "our".
 *   - The Campuses page shows materials, never a room with children in it.
 *   - Campuses, Gallery, Educators and Testimonials keep their honest "not yet"
 *     states, which is where a reader is actually told what does not exist yet.
 *   - The Shastri family pages take no stock photography at all.
 * Provenance for every file is kept in image-credits.json, which is a licence
 * ledger for the team and not something a parent is shown.
 * See docs/decisions-and-todos.md item C-04.
 *
 * HOW IT RENDERS
 * One <picture> per image: AVIF, then WebP, then JPEG, each with a srcset built
 * from the widths actually present on disk (see src/data/media.ts, generated by
 * scripts/build-image-manifest.mjs). Intrinsic width and height are always
 * emitted so nothing shifts while the file arrives, and the average colour of
 * the image is painted underneath so the space is never blank white.
 */

const IMAGE_BASE = '/images'

const sourceSet = (name: PhotoName, extension: 'avif' | 'webp' | 'jpg') => {
  const meta = photos[name]
  return meta.widths
    .map((width) => {
      // The largest render is stored unsuffixed by the sourcing toolkit.
      const file = width === meta.width ? `${name}.${extension}` : `${name}-${width}w.${extension}`
      return `${IMAGE_BASE}/${file} ${width}w`
    })
    .join(', ')
}

export type PhotoProps = {
  name: PhotoName
  /** Overrides the manifest's alt text when the same image says something
   *  different in a new context. Pass "" only for genuinely decorative use. */
  alt?: string
  className?: string
  /** Applied to the <img> itself; use for object-position tuning. */
  imgClassName?: string
  /**
   * The `sizes` attribute. Getting this wrong is the single most expensive
   * mistake available here, so every caller states it.
   */
  sizes: string
  /** The LCP image. Loads eagerly at high priority and is never lazy. */
  priority?: boolean
  /** CSS aspect-ratio for the frame, e.g. "3/4". Defaults to the file's own. */
  ratio?: string
  /**
   * Take height from the container instead of from an aspect ratio. Used by
   * the page header, whose height is fixed at 40vh and must not shift because
   * one route's photograph happens to be a different shape from another's.
   */
  fill?: boolean
  /**
   * Aspect ratio expressed as Tailwind classes rather than an inline style, so
   * it can change per breakpoint. A single `ratio` cannot do that, and a
   * cinematic band that reads well at 1440px collapses to a 167px sliver on a
   * phone. Takes precedence over `ratio`.
   */
  ratioClassName?: string
  /** object-position, for when the subject is not centred. */
  focus?: string
  style?: CSSProperties
}

export function Photo({
  name,
  alt,
  className,
  imgClassName,
  sizes,
  priority = false,
  ratio,
  fill = false,
  ratioClassName,
  focus,
  style,
}: PhotoProps) {
  const meta = photos[name]
  const aspect = ratio ?? `${meta.width} / ${meta.height}`
  const inlineAspect = fill || ratioClassName ? undefined : aspect

  return (
    <span
      className={cn(
        'relative block overflow-hidden',
        fill && 'size-full',
        ratioClassName,
        className,
      )}
      style={{ aspectRatio: inlineAspect, backgroundColor: meta.tint, ...style }}
    >
      <picture>
        <source type="image/avif" srcSet={sourceSet(name, 'avif')} sizes={sizes} />
        <source type="image/webp" srcSet={sourceSet(name, 'webp')} sizes={sizes} />
        <img
          src={`${IMAGE_BASE}/${name}.jpg`}
          srcSet={sourceSet(name, 'jpg')}
          sizes={sizes}
          alt={alt ?? meta.alt}
          width={meta.width}
          height={meta.height}
          loading={priority ? 'eager' : 'lazy'}
          decoding={priority ? 'sync' : 'async'}
          fetchPriority={priority ? 'high' : 'auto'}
          draggable={false}
          className={cn(
            'absolute inset-0 size-full object-cover',
            focus ? undefined : 'object-center',
            imgClassName,
          )}
          style={focus ? { objectPosition: focus } : undefined}
        />
      </picture>
    </span>
  )
}

/* ==========================================================================
   Framed compositions
   ========================================================================== */

export type PhotoShape =
  | 'arch'
  | 'leaf'
  | 'leaf-alt'
  | 'cut'
  | 'cut-alt'
  | 'crest'
  | 'crest-alt'
  | 'petal'
  | 'pill'
  | 'blob'
  | 'blob-alt'
  | 'blob-soft'
  | 'soft'
  | 'rounded'

/** Exported so ambient video can wear exactly the same silhouettes. */
export const shapeClasses: Record<PhotoShape, string> = {
  arch: 'shape-arch',
  leaf: 'shape-leaf',
  'leaf-alt': 'shape-leaf-alt',
  cut: 'shape-cut',
  'cut-alt': 'shape-cut-alt',
  crest: 'shape-crest',
  'crest-alt': 'shape-crest-alt',
  petal: 'shape-petal',
  pill: 'shape-pill',
  blob: 'shape-blob',
  'blob-alt': 'shape-blob-alt',
  'blob-soft': 'shape-blob-soft',
  soft: 'shape-soft',
  rounded: 'rounded-xl',
}

/**
 * A photograph in one of the house silhouettes, with a small hover zoom.
 *
 * The zoom is on the <img> and the shape is on the frame, so the browser
 * animates a transform inside an already-clipped box — no layout, no repaint of
 * the surrounding page.
 */
export function ShapedPhoto({
  shape = 'rounded',
  className,
  interactive = false,
  ...photo
}: PhotoProps & { shape?: PhotoShape; interactive?: boolean }) {
  return (
    <Photo
      {...photo}
      className={cn(shapeClasses[shape], 'group/photo', className)}
      imgClassName={cn(
        interactive &&
          'transition-transform duration-700 ease-out-soft group-hover/photo:scale-[1.04] motion-reduce:transition-none motion-reduce:group-hover/photo:scale-100',
        photo.imgClassName,
      )}
    />
  )
}

/**
 * A photograph on a plate of colour: a crisp shape slid off one corner
 * (`plate`), or an even surround (`ring`). Never a blurred glow — see `depth`.
 */
export function PhotoOnColour({
  colour = 'orange',
  shape = 'leaf',
  matShape,
  spread = 'edge',
  depth = 'plate',
  lean = 'none',
  className,
  children,
  ...photo
}: PhotoProps & {
  colour?: 'orange' | 'green' | 'sky' | 'brand' | 'mist'
  shape?: PhotoShape
  /**
   * The silhouette of the colour behind the photograph, when it should differ
   * from the photograph's own.
   *
   * This is what makes a picture read as a cut-out stuck onto a colour block
   * rather than as a photograph with a coloured border: when the two outlines
   * disagree, the colour escapes at some corners and is swallowed at others,
   * and the eye reads two objects instead of one thick edge. Matching the
   * photograph's shape — the default — is the quiet version.
   */
  matShape?: PhotoShape
  /**
   * How far the plate is allowed out from behind the picture.
   *
   * `edge` is the original: a 12px slide that reads as a printed sticker.
   * `block` pushes the colour well clear on two sides so it becomes a shape in
   * its own right, which is the treatment that needs `matShape` to earn it.
   * Anything using `block` must have room beside it — the plate is `absolute`
   * and its parent does not clip, so a full-width picture in a narrow gutter
   * would push the document sideways.
   */
  spread?: 'edge' | 'block'
  /**
   * How the colour sits behind the photograph. `plate` keeps it crisp and
   * slides it off a corner; `ring` surrounds the picture evenly. There is no
   * blurred glow option: a soft bloom around a picture read as a shadow that
   * did not belong to anything.
   */
  depth?: 'plate' | 'ring'
  /** Which corner a `plate` slides towards. */
  lean?: 'left' | 'right' | 'none'
  children?: ReactNode
}) {
  /**
   * Two weights of colour, and which one is used depends on how much of it
   * shows.
   *
   * A 200 is right for a 12px reveal: at that width a saturated block reads as
   * a mis-registered print. Once the plate is out far enough to be a shape of
   * its own it has to carry that weight, and a 200 just looks washed out — so
   * `block` steps up to the 300s and 400s, which is the register the reference
   * material uses for a photograph sitting on a colour.
   */
  const mat = {
    orange: 'bg-orange-200',
    green: 'bg-green-200',
    sky: 'bg-sky-200',
    brand: 'bg-brand-200',
    mist: 'bg-mist-300',
  }
  const matBold = {
    orange: 'bg-orange-400',
    green: 'bg-green-400',
    sky: 'bg-sky-400',
    brand: 'bg-brand-400',
    mist: 'bg-mist-500',
  }
  // Down and outward, so the pair of them leans away from the centre of a
  // composition rather than both leaning the same way.
  const plateShift = {
    edge: {
      left: '-translate-x-3 translate-y-3',
      right: 'translate-x-3 translate-y-3',
      none: 'translate-y-3',
    },
    // Scale as well as translate: a plate that only slides shows colour on two
    // sides and nothing on the other two, which reads as a drop shadow. Growing
    // it first means the colour clears the picture all the way round and the
    // lean decides only which way it clears furthest.
    //
    // Held back to `lg` and above, where a picture sits in a column with a
    // gutter beside it. Below that the layout is one column at ~92vw and the
    // extra 18px a side has nowhere to go: the plate is absolutely positioned,
    // nothing clips it, and it would add horizontal scroll to the document.
    // Under `lg` this is simply the `edge` treatment.
    block: {
      left: '-translate-x-3 translate-y-3 lg:-translate-x-4 lg:translate-y-4 lg:scale-[1.05]',
      right: 'translate-x-3 translate-y-3 lg:translate-x-4 lg:translate-y-4 lg:scale-[1.05]',
      none: 'translate-y-3 lg:translate-y-4 lg:scale-[1.05]',
    },
  }

  /**
   * The colour as a solid shape the photograph sits *inside*, rather than a
   * plate behind it.
   *
   * This is the treatment the reference material actually uses: a child on a
   * solid disc of colour. Two things follow from building it as padding instead
   * of as an absolutely positioned sibling.
   *
   * IT CANNOT LOOK LIKE A SHADOW. An offset plate shows colour on two sides and
   * nothing on the other two, and the eye reads that as a drop shadow in an odd
   * hue no matter how saturated it is — which is exactly what the offset version
   * was reported as. An even surround has no direction to misread.
   *
   * IT CANNOT PUSH THE PAGE SIDEWAYS. The offset plate was `absolute` and
   * nothing clipped it, so its throw was added to the document's scroll width;
   * measured at 320, 390, 768, 1024, 1100 and 1280 it overflowed at every one.
   * A padded box is in normal flow, so the colour is part of the element's own
   * width and there is no geometry left to escape.
   *
   * What it still is not: a cut-out. The reference has the child breaking the
   * top of the disc, which needs a subject on a transparent background. These
   * are rectangular documentary photographs, so the picture is clipped to the
   * shape and the colour surrounds it evenly.
   *
   * DO NOT USE A 999px SHAPE HERE — `arch`, `pill`, `crest`, `crest-alt`. The
   * frame and the picture inside it are two boxes of different sizes wearing
   * the same `border-radius`, and CSS resolves an over-large radius against
   * each box's own dimensions: it scales every corner down by the factor that
   * makes adjacent radii fit the side they share. At the hero's size that gave
   * the 288x453 frame a 64px arch and the 248x413 photograph inside it a 50px
   * one, so the two arcs were not parallel and the band of colour went from
   * 20px at the sides to 34px over the top. It reads as a mistake, because it
   * is one. Shapes built from fixed rem radii — `leaf`, `cut`, `rounded` — are
   * never clamped at these sizes and stay parallel.
   */
  if (depth === 'ring') {
    return (
      <div
        className={cn(
          // Generous on purpose. At 10px the colour reads as a border on the
          // photograph; the reference wants a shape the photograph is sitting
          // on, and that needs enough of it to register as an area.
          'p-3 sm:p-5',
          shapeClasses[matShape ?? shape],
          matBold[colour],
          className,
        )}
      >
        <ShapedPhoto {...photo} shape={shape} interactive className="shadow-photo" />
        {children}
      </div>
    )
  }

  return (
    <div className={cn('relative', className)}>
      <div
        aria-hidden="true"
        className={cn(
          'absolute inset-0 transition-transform duration-500 ease-out-soft',
          shapeClasses[matShape ?? shape],
          spread === 'block' ? matBold[colour] : mat[colour],
          plateShift[spread][lean],
        )}
      />
      <ShapedPhoto
        {...photo}
        shape={shape}
        interactive
        className="relative shadow-photo"
      />
      {children}
    </div>
  )
}

/**
 * Photograph plus a caption that says what the reader is looking at.
 * Used wherever the image is doing explanatory work rather than atmosphere.
 */
export function PhotoFigure({
  caption,
  className,
  shape = 'rounded',
  ...photo
}: PhotoProps & { caption: ReactNode; shape?: PhotoShape; className?: string }) {
  return (
    <figure className={cn('flex flex-col gap-3', className)}>
      <ShapedPhoto {...photo} shape={shape} interactive />
      <figcaption className="text-small leading-relaxed text-ink-400">{caption}</figcaption>
    </figure>
  )
}

